### ISSUE TITLE
do we allow git-lfs in renku repo when building container ?

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/nb2workflow#73]

**Comment by volodymyrss** [comment]
> This changes a lot the way we deploy backends.

Using a volume is not really too hard and it's useful since overflowing images is the principal limiting factor for these backends https://github.com/oda-hub/nb2workflow/issues/74

Fetching LFS upon run is not at all complex, I can try it https://github.com/oda-hub/nb2workflow/issues/75

> For the time being, the example is https://renkulab.io/gitlab/astronomy/mmoda/fermi @andriineronov included the catalog in the repo as it is quite small (8MB). But it's still large enough for Renku to only allow it through lfs. Now the workflow backend is broken.
> 
> Should we probably allow using lfs, but just add global repo size limit in nb2workflow.deploy ?
> 
> Or we can allow it to be configurable through mmoda.yaml

ok, for a small data like that there is no problem to just fetch it. Do you want to add it?

**Comment by dsavchenko** [comment]
If we will succeed with #74 and #75 then there's no real need to include it in container. Still, I would prefer to have it as an option, so I will do it

**Comment by dsavchenko** [comment]
Finally, it's not really optional, because `git clone` downloads lfs files as long as git-lfs is installed

**Comment by volodymyrss** [comment]
we could skip it though https://stackoverflow.com/questions/42019529/how-to-clone-pull-a-git-repository-ignoring-lfs
but it's fine if it's about 8Mb
